set windows-shell := ["cmd.exe", "/c"]
setup:
    npm run setup

lint:
    npm run lint

typecheck:
    npm run typecheck

test:
    npm run test

eval:
    npm run eval

security:
    npm run security

build:
    npm run build

start:
    npm run start

changelog:
    git cliff -o CHANGELOG.md

ci:
    npm run ci
